services:
  postgres:
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_project_2
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres:5432/go_project_2?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for-it.sh", "postgres:5432", "--", "/app/start.sh"]
    command: [ "/app/main" ]
volumes:
  data-volume:
