version: '3.8'

services:
  postgres:
    image: postgres:13.1-alpine
    restart: always
    networks:
      - db
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - db
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

networks:
  db:

volumes:
  postgres_data:
